/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sclk.scwms.web.form;

import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-23-2010
 * 
 * XDoclet definition:
 * @struts.form name="cargoForm"
 */
public class CargoEditForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** unit property */
	private String unit;
	private List unitList;
	/** category property */
	private String category;
	private List categoryList;
	/** size property */
	private String size;

	/** name property */
	private String name;

	/** weight property */
	private String weight;

	/** id property */
	private String id;

	/** number property */
	private String number;
	private String jsonList;
	
	private String serialNumber;
	private String customerName;
	private String customerId;
	private List customerList;
	private String personHandling;
	private String time;
	private List cargoList;
	
	private String batchNumber;
	private String dateProduce;
	private String quantity;
	private String totalWeight;
	private String locationId;
	
	private String unitPrice;
	private String countUnit;
	private String totalPrice;
	
	private String grossWeight;
	private String totalGrossWeight;
	
	private String chargeList;
	/*
	 * Generated Methods
	 */

	public String getChargeList() {
		return chargeList;
	}

	public void setChargeList(String chargeList) {
		this.chargeList = chargeList;
	}

	public String getCountUnit() {
		return countUnit;
	}

	public void setCountUnit(String countUnit) {
		this.countUnit = countUnit;
	}

	public String getSerialNumber() {
		return serialNumber;
	}

	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	public String getCustomerName() {
		return customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getPersonHandling() {
		return personHandling;
	}

	public void setPersonHandling(String personHandling) {
		this.personHandling = personHandling;
	}

	public String getTime() {
		return time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the unit.
	 * @return String
	 */
	public String getUnit() {
		return unit;
	}

	/** 
	 * Set the unit.
	 * @param unit The unit to set
	 */
	public void setUnit(String unit) {
		this.unit = unit;
	}

	/** 
	 * Returns the category.
	 * @return String
	 */
	public String getCategory() {
		return category;
	}

	/** 
	 * Set the category.
	 * @param category The category to set
	 */
	public void setCategory(String category) {
		this.category = category;
	}

	/** 
	 * Returns the size.
	 * @return String
	 */
	public String getSize() {
		return size;
	}

	/** 
	 * Set the size.
	 * @param size The size to set
	 */
	public void setSize(String size) {
		this.size = size;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/** 
	 * Returns the weight.
	 * @return String
	 */
	public String getWeight() {
		return weight;
	}

	/** 
	 * Set the weight.
	 * @param weight The weight to set
	 */
	public void setWeight(String weight) {
		this.weight = weight;
	}

	/** 
	 * Returns the id.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/** 
	 * Returns the number.
	 * @return String
	 */
	public String getNumber() {
		return number;
	}

	/** 
	 * Set the number.
	 * @param number The number to set
	 */
	public void setNumber(String number) {
		this.number = number;
	}

	public List getUnitList() {
		return unitList;
	}

	public void setUnitList(List unitList) {
		this.unitList = unitList;
	}

	public List getCategoryList() {
		return categoryList;
	}

	public void setCategoryList(List categoryList) {
		this.categoryList = categoryList;
	}

	public String getJsonList() {
		return jsonList;
	}

	public void setJsonList(String jsonList) {
		this.jsonList = jsonList;
	}

	public List getCargoList() {
		return cargoList;
	}

	public void setCargoList(List cargoList) {
		this.cargoList = cargoList;
	}

	public String getCustomerId() {
		return customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	public List getCustomerList() {
		return customerList;
	}

	public void setCustomerList(List customerList) {
		this.customerList = customerList;
	}

	public String getBatchNumber() {
		return batchNumber;
	}

	public void setBatchNumber(String batchNumber) {
		this.batchNumber = batchNumber;
	}

	public String getDateProduce() {
		return dateProduce;
	}

	public void setDateProduce(String dateProduce) {
		this.dateProduce = dateProduce;
	}

	public String getQuantity() {
		return quantity;
	}

	public void setQuantity(String quantity) {
		this.quantity = quantity;
	}

	public String getTotalWeight() {
		return totalWeight;
	}

	public void setTotalWeight(String totalWeight) {
		this.totalWeight = totalWeight;
	}

	public String getLocationId() {
		return locationId;
	}

	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}

	public String getUnitPrice() {
		return unitPrice;
	}

	public void setUnitPrice(String unitPrice) {
		this.unitPrice = unitPrice;
	}

	public String getTotalPrice() {
		return totalPrice;
	}

	public void setTotalPrice(String totalPrice) {
		this.totalPrice = totalPrice;
	}

	public String getGrossWeight() {
		return grossWeight;
	}

	public void setGrossWeight(String grossWeight) {
		this.grossWeight = grossWeight;
	}

	public String getTotalGrossWeight() {
		return totalGrossWeight;
	}

	public void setTotalGrossWeight(String totalGrossWeight) {
		this.totalGrossWeight = totalGrossWeight;
	}



		
}