/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sclk.scwms.web.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-24-2010
 * 
 * XDoclet definition:
 * @struts.form name="contractEditForm"
 */
public class ContractEditForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** signingDate property */
	private String signingDate;

	/** type property */
	private String type;

	/** validity property */
	private String validity;

	/** effectiveDate property */
	private String effectiveDate;

	/** comment property */
	private String comment;

	/** status property */
	private String status;

	/** endDate property */
	private String endDate;

	/** id property */
	private String id;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the signingDate.
	 * @return String
	 */
	public String getSigningDate() {
		return signingDate;
	}

	/** 
	 * Set the signingDate.
	 * @param signingDate The signingDate to set
	 */
	public void setSigningDate(String signingDate) {
		this.signingDate = signingDate;
	}

	/** 
	 * Returns the type.
	 * @return String
	 */
	public String getType() {
		return type;
	}

	/** 
	 * Set the type.
	 * @param type The type to set
	 */
	public void setType(String type) {
		this.type = type;
	}

	/** 
	 * Returns the validity.
	 * @return String
	 */
	public String getValidity() {
		return validity;
	}

	/** 
	 * Set the validity.
	 * @param validity The validity to set
	 */
	public void setValidity(String validity) {
		this.validity = validity;
	}

	/** 
	 * Returns the effectiveDate.
	 * @return String
	 */
	public String getEffectiveDate() {
		return effectiveDate;
	}

	/** 
	 * Set the effectiveDate.
	 * @param effectiveDate The effectiveDate to set
	 */
	public void setEffectiveDate(String effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	/** 
	 * Returns the comment.
	 * @return String
	 */
	public String getComment() {
		return comment;
	}

	/** 
	 * Set the comment.
	 * @param comment The comment to set
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}

	/** 
	 * Returns the status.
	 * @return String
	 */
	public String getStatus() {
		return status;
	}

	/** 
	 * Set the status.
	 * @param status The status to set
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/** 
	 * Returns the endDate.
	 * @return String
	 */
	public String getEndDate() {
		return endDate;
	}

	/** 
	 * Set the endDate.
	 * @param endDate The endDate to set
	 */
	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	/** 
	 * Returns the id.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}
}