/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sclk.scwms.web.form;

import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-23-2010
 * 
 * XDoclet definition:
 * @struts.form name="customerForm"
 */
public class CustomerEditForm extends ActionForm {
	/*
	 * Generated fields
	 */
	private String id;
	/** memo property */
	private String memo;

	/** contact property */
	private String contact;

	/** type property */
	private String type;
	private List typeList;

	/** account property */
	private String account;

	/** postcode property */
	private String postcode;

	/** phoneNumber1 property */
	private String phoneNumber1;

	/** address property */
	private String address;

	/** dutyId property */
	private String dutyId;

	/** openingBank property */
	private String openingBank;

	/** fax property */
	private String fax;

	/** phoneNumber2 property */
	private String phoneNumber2;

	/** name property */
	private String name;
	private String shortName;
	private String symbol;
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the memo.
	 * @return String
	 */
	public String getMemo() {
		return memo;
	}

	/** 
	 * Set the memo.
	 * @param memo The memo to set
	 */
	public void setMemo(String memo) {
		this.memo = memo;
	}

	/** 
	 * Returns the contact.
	 * @return String
	 */
	public String getContact() {
		return contact;
	}

	/** 
	 * Set the contact.
	 * @param contact The contact to set
	 */
	public void setContact(String contact) {
		this.contact = contact;
	}

	/** 
	 * Returns the type.
	 * @return String
	 */
	public String getType() {
		return type;
	}

	/** 
	 * Set the type.
	 * @param type The type to set
	 */
	public void setType(String type) {
		this.type = type;
	}

	/** 
	 * Returns the account.
	 * @return String
	 */
	public String getAccount() {
		return account;
	}

	/** 
	 * Set the account.
	 * @param account The account to set
	 */
	public void setAccount(String account) {
		this.account = account;
	}

	/** 
	 * Returns the postcode.
	 * @return String
	 */
	public String getPostcode() {
		return postcode;
	}

	/** 
	 * Set the postcode.
	 * @param postcode The postcode to set
	 */
	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	/** 
	 * Returns the phoneNumber1.
	 * @return String
	 */
	public String getPhoneNumber1() {
		return phoneNumber1;
	}

	/** 
	 * Set the phoneNumber1.
	 * @param phoneNumber1 The phoneNumber1 to set
	 */
	public void setPhoneNumber1(String phoneNumber1) {
		this.phoneNumber1 = phoneNumber1;
	}

	/** 
	 * Returns the address.
	 * @return String
	 */
	public String getAddress() {
		return address;
	}

	/** 
	 * Set the address.
	 * @param address The address to set
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/** 
	 * Returns the dutyId.
	 * @return String
	 */
	public String getDutyId() {
		return dutyId;
	}

	/** 
	 * Set the dutyId.
	 * @param dutyId The dutyId to set
	 */
	public void setDutyId(String dutyId) {
		this.dutyId = dutyId;
	}

	/** 
	 * Returns the openingBank.
	 * @return String
	 */
	public String getOpeningBank() {
		return openingBank;
	}

	/** 
	 * Set the openingBank.
	 * @param openingBank The openingBank to set
	 */
	public void setOpeningBank(String openingBank) {
		this.openingBank = openingBank;
	}

	/** 
	 * Returns the fax.
	 * @return String
	 */
	public String getFax() {
		return fax;
	}

	/** 
	 * Set the fax.
	 * @param fax The fax to set
	 */
	public void setFax(String fax) {
		this.fax = fax;
	}

	/** 
	 * Returns the phoneNumber2.
	 * @return String
	 */
	public String getPhoneNumber2() {
		return phoneNumber2;
	}

	/** 
	 * Set the phoneNumber2.
	 * @param phoneNumber2 The phoneNumber2 to set
	 */
	public void setPhoneNumber2(String phoneNumber2) {
		this.phoneNumber2 = phoneNumber2;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	public List getTypeList() {
		return typeList;
	}

	public void setTypeList(List typeList) {
		this.typeList = typeList;
	}

	

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getShortName() {
		return shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public String getSymbol() {
		return symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}
}