/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sclk.scwms.web.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-19-2010
 * 
 * XDoclet definition:
 * @struts.form name="dictionaryEditForm"
 */
public class DictionaryEditForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** memo property */
	private String memo;

	/** parentId property */
	private String parentId;

	/** orderId property */
	private int orderId;

	/** indexId property */
	private String indexId;

	/** name property */
	private String name;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the memo.
	 * @return String
	 */
	public String getMemo() {
		return memo;
	}

	/** 
	 * Set the memo.
	 * @param memo The memo to set
	 */
	public void setMemo(String memo) {
		this.memo = memo;
	}

	/** 
	 * Returns the parentId.
	 * @return String
	 */
	public String getParentId() {
		return parentId;
	}

	/** 
	 * Set the parentId.
	 * @param parentId The parentId to set
	 */
	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	/** 
	 * Returns the orderId.
	 * @return int
	 */
	public int getOrderId() {
		return orderId;
	}

	/** 
	 * Set the orderId.
	 * @param orderId The orderId to set
	 */
	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	/** 
	 * Returns the indexId.
	 * @return String
	 */
	public String getIndexId() {
		return indexId;
	}

	/** 
	 * Set the indexId.
	 * @param indexId The indexId to set
	 */
	public void setIndexId(String indexId) {
		this.indexId = indexId;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}
}