/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sclk.scwms.web.form;

import java.util.ArrayList;
import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-19-2010
 * 
 * XDoclet definition:
 * @struts.form name="dictionaryForm"
 */
public class DictionaryForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** dicTree property */
	private ArrayList dicTree;

	/** dicList property */
	private ArrayList dicList;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the dicTree.
	 * @return ArrayList
	 */
	public ArrayList getDicTree() {
		return dicTree;
	}

	/** 
	 * Set the dicTree.
	 * @param dicTree The dicTree to set
	 */
	public void setDicTree(ArrayList dicTree) {
		this.dicTree = dicTree;
	}

	/** 
	 * Returns the dicList.
	 * @return ArrayList
	 */
	public ArrayList getDicList() {
		return dicList;
	}

	/** 
	 * Set the dicList.
	 * @param dicList The dicList to set
	 */
	public void setDicList(ArrayList dicList) {
		this.dicList = dicList;
	}
}