/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sclk.scwms.web.form;

import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-23-2010
 * 
 * XDoclet definition:
 * @struts.form name="warehouseForm"
 */
public class WarehouseEditForm extends ActionForm {
	/*
	 * Generated fields
	 */
	
	/** id property */
	private String id;
	/** name property */
	private String name;
	/** serialNumber property */
	private String serialNumber;

	private String serialKey;
	
	private String parentKey;
	
	
	/** type property */
	private String type;
	private List typeList;

	private String temperature;
	
	
	/** size property */
	private String size;
	/** orderId property */
	private Integer orderId;

	/** area property */
	private String area;
	/** volume property */
	private String volume;
	
	private String length;
	private String width;
	private String height;
	
	/** memo property */
	private String memo;
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the volume.
	 * @return String
	 */
	public String getVolume() {
		return volume;
	}

	/** 
	 * Set the volume.
	 * @param volume The volume to set
	 */
	public void setVolume(String volume) {
		this.volume = volume;
	}

	/** 
	 * Returns the memo.
	 * @return String
	 */
	public String getMemo() {
		return memo;
	}

	/** 
	 * Set the memo.
	 * @param memo The memo to set
	 */
	public void setMemo(String memo) {
		this.memo = memo;
	}

	/** 
	 * Returns the type.
	 * @return String
	 */
	public String getType() {
		return type;
	}

	/** 
	 * Set the type.
	 * @param type The type to set
	 */
	public void setType(String type) {
		this.type = type;
	}

	

	public Integer getOrderId() {
		return orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	/** 
	 * Returns the size.
	 * @return String
	 */
	public String getSize() {
		return size;
	}

	/** 
	 * Set the size.
	 * @param size The size to set
	 */
	public void setSize(String size) {
		this.size = size;
	}

	/** 
	 * Returns the area.
	 * @return String
	 */
	public String getArea() {
		return area;
	}

	/** 
	 * Set the area.
	 * @param area The area to set
	 */
	public void setArea(String area) {
		this.area = area;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/** 
	 * Returns the serialNumber.
	 * @return String
	 */
	public String getSerialNumber() {
		return serialNumber;
	}

	/** 
	 * Set the serialNumber.
	 * @param serialNumber The serialNumber to set
	 */
	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	/** 
	 * Returns the id.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	public List getTypeList() {
		return typeList;
	}

	public void setTypeList(List typeList) {
		this.typeList = typeList;
	}

	public String getSerialKey() {
		return serialKey;
	}

	public void setSerialKey(String serialKey) {
		this.serialKey = serialKey;
	}

	public String getParentKey() {
		return parentKey;
	}

	public void setParentKey(String parentKey) {
		this.parentKey = parentKey;
	}

	public String getTemperature() {
		return temperature;
	}

	public void setTemperature(String temperature) {
		this.temperature = temperature;
	}

	public String getLength() {
		return length;
	}

	public void setLength(String length) {
		this.length = length;
	}

	public String getWidth() {
		return width;
	}

	public void setWidth(String width) {
		this.width = width;
	}

	public String getHeight() {
		return height;
	}

	public void setHeight(String height) {
		this.height = height;
	}
}