/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sclk.scwms.web.action;

import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.sclk.scwms.common.StringUtil;
import com.sclk.scwms.model.Location;
import com.sclk.scwms.service.CargoManager;
import com.sclk.scwms.vo.CargoRecordItemsVO;
import com.sclk.scwms.vo.CargoVO;
import com.sclk.scwms.web.form.CargoForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-24-2010
 * 
 * XDoclet definition:
 * @struts.action path="/customer" name="customerForm" input="/jsp/customer.jsp" scope="request" validate="true"
 */
public class CargoAction extends BaseAction {
	
	private CargoManager manager;

    public void setManager(CargoManager manager) {
    	this.manager = manager;
    }
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward view(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		CargoForm cargoForm = (CargoForm) form;// TODO Auto-generated method stub
		String type  = request.getParameter("type");
		
		
		if(type != null && type.equals("readOnly")){
			return mapping.findForward("readOnly");
		}else{
			List list = manager.getCargoesVOList();
			
			request.setAttribute("cargo.list", list);
			return mapping.findForward("view");
		}
	}
	public ActionForward query(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws UnsupportedEncodingException {
		CargoForm cargoForm = (CargoForm) form;// TODO Auto-generated method stub
		String keyword  = request.getParameter("keyword");
		if(keyword!=null){
			keyword = new String(keyword.getBytes("ISO8859_1"),"utf-8");
		}
		List list = manager.findBykeyword(keyword);
		
		request.setAttribute("keyword",keyword);
		request.setAttribute("cargo.list", list);
		
		return mapping.findForward("query");
		
	}
	public ActionForward items(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		CargoForm cargoForm = (CargoForm) form;// TODO Auto-generated method stub
		String cargoId  = request.getParameter("cargoId");
		String locationId = request.getParameter("locationId");
		
		CargoVO cargoVO = manager.getCargoVO(StringUtil.stringToInteger(cargoId));
		
		ArrayList<Location> listLocation = new ArrayList<Location>();
		
		List<CargoRecordItemsVO> list = manager.getCargoItemsList(cargoId,locationId);
		
		for(CargoRecordItemsVO vo:list){
			
			Location location = new Location();
			if(vo.getLocationId() == null){
				location.setId(1);
			}else{
				location.setId(vo.getLocationId());
			}
			if(vo.getLocationId() == null){
				location.setWarehouseName("");
			}else{
				location.setWarehouseName(vo.getLocationName());
			}
			listLocation.add(location);
		}
		
		Set set = new HashSet();
		
		set.addAll(listLocation);//将list添加到set中
		
		listLocation.clear();//清除list中的数据
		
		listLocation.addAll(set);//将set中的数据重新写回list中
		
		request.setAttribute("cargoItems.list", list);
		request.setAttribute("cargoVO", cargoVO);
		request.setAttribute("listLocation", listLocation);
		
		return mapping.findForward("items");
		
	}
}