/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sclk.scwms.web.action;

import java.util.Calendar;
import java.util.Date;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.sclk.scwms.common.ConfigUtil;
import com.sclk.scwms.common.DateUtil;
import com.sclk.scwms.common.JsonUtil;
import com.sclk.scwms.common.StringUtil;
import com.sclk.scwms.model.Customer;
import com.sclk.scwms.service.CustomerManager;
import com.sclk.scwms.service.StockRecordManager;
import com.sclk.scwms.vo.CargoVO;
import com.sclk.scwms.web.form.CustomerInventoryForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-06-2010
 * 
 * XDoclet definition:
 * @struts.action path="/stockItems" name="stockItemsForm" input="/jsp/stockItems.jsp" scope="request" validate="true"
 */
public class CustomerInventoryAction extends BaseAction {
	
	private StockRecordManager stockRecordManager;

    public void setStockRecordManager(StockRecordManager manager) {
    	this.stockRecordManager = manager;
    }
    
    private CustomerManager customerManager;

    public void setCustomerManager(CustomerManager manager) {
    	this.customerManager = manager;
    }
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward view(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		CustomerInventoryForm customerInventoryForm = (CustomerInventoryForm) form;// TODO Auto-generated method stub
		String customerId = request.getParameter("customerId");
		String isDL = request.getParameter("isDL");
		
		String eDate = new String();
		Date d = new Date();
	
		eDate = DateUtil.datetimeToStr("yyyy-MM-dd",d);
		boolean b = StringUtil.stringToBoolean(isDL);
		List<CargoVO> cargoesList = stockRecordManager.getCustomerInventoryList(customerId,ConfigUtil.sDate,eDate,b);
		Customer c = customerManager.getCustomer(StringUtil.stringToInteger(customerId));
		
		request.setAttribute("customer", c);
		request.setAttribute("cargoes.list", cargoesList);
		
		return mapping.findForward("view");
	}
	
	public ActionForward inventory(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		CustomerInventoryForm customerInventoryForm = (CustomerInventoryForm) form;// TODO Auto-generated method stub
		
		String eDate = new String();
		Date d = new Date();
	
		eDate = DateUtil.datetimeToStr("yyyy-MM-dd",d);
		
		List<CargoVO> cargoesList = stockRecordManager.getCustomerInventoryList("",ConfigUtil.sDate,eDate,true);
		
		request.setAttribute("cargoes.list", cargoesList);
		
		return mapping.findForward("inventory");
	}
}