/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sclk.scwms.web.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.sclk.scwms.model.Syscode;
import com.sclk.scwms.service.CustomerManager;
import com.sclk.scwms.service.SyscodeManager;
import com.sclk.scwms.web.form.CustomerForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-24-2010
 * 
 * XDoclet definition:
 * @struts.action path="/customer" name="customerForm" input="/jsp/customer.jsp" scope="request" validate="true"
 */
public class CustomerAction extends BaseAction {
	
	private CustomerManager manager;

    public void setManager(CustomerManager manager) {
    	this.manager = manager;
    }
    
    
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward view(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		CustomerForm customerForm = (CustomerForm) form;// TODO Auto-generated method stub
		
		List list = manager.getCustomers();
		
		request.setAttribute("customer.list", list);
		
		return mapping.findForward("view");
		
	}
}