/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sclk.scwms.web.action;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.sclk.scwms.common.DateUtil;
import com.sclk.scwms.common.JsonUtil;
import com.sclk.scwms.common.StringUtil;
import com.sclk.scwms.model.Customer;
import com.sclk.scwms.service.CargoManager;
import com.sclk.scwms.service.CustomerManager;
import com.sclk.scwms.service.StockRecordManager;
import com.sclk.scwms.vo.CargoVO;
import com.sclk.scwms.vo.MonthTotalVO;
import com.sclk.scwms.vo.StockRecordVO;
import com.sclk.scwms.web.form.DetailChargeForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-06-2010
 * 
 * XDoclet definition:
 * @struts.action path="/stockItems" name="stockItemsForm" input="/jsp/stockItems.jsp" scope="request" validate="true"
 */
public class DetailChargeAction extends BaseAction {
	
	private StockRecordManager stockRecordManager;

    public void setStockRecordManager(StockRecordManager manager) {
    	this.stockRecordManager = manager;
    }
    
    private CustomerManager customerManager;

    public void setCustomerManager(CustomerManager manager) {
    	this.customerManager = manager;
    }
    
    private CargoManager cargoManager;

    public void setCargoManager(CargoManager manager) {
    	this.cargoManager = manager;
    }
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response          
	 * @return ActionForward
	 */
	public ActionForward view(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DetailChargeForm detailChargeForm = (DetailChargeForm) form;// TODO Auto-generated method stub
		
		String customerId = request.getParameter("customerId");
		String month = request.getParameter("month");
		
		
		Date sDate = new Date();
		Date eDate = new Date();
		Date mDate = new Date();
		Date midDate = new Date();
		Date d = new Date();
		
		if(month != null){
			d = DateUtil.stringToDate("yyyyMM", month);
			
		}
		
		Calendar  ca = Calendar.getInstance();
		
		ca.setTime(d);
		ca.add(Calendar.MONTH, -1);
		mDate = ca.getTime();
		ca.set(Calendar.DAY_OF_MONTH, 21);
		sDate = ca.getTime();
		
		ca.add(Calendar.MONTH, 1);
		ca.set(Calendar.DAY_OF_MONTH, 6);
		midDate = ca.getTime();
		ca.set(Calendar.DAY_OF_MONTH, 20);
		eDate =  ca.getTime();
		
		int day_1 = DateUtil.getDays(sDate, midDate);
		int day_2 = DateUtil.getDays(midDate, eDate)+1;
		
		
		List<Date> dateList = new ArrayList();
		/*Calendar  cs = Calendar.getInstance();
		Calendar  ce = Calendar.getInstance();
		cs.setTime(sDate);
		ce.setTime(eDate);*/
		
		
	/*	for(;!cs.after(ce);cs.add(Calendar.DAY_OF_MONTH, 1)){
			dateList.add(cs.getTime());
			
		}
		*/
		
		Customer c = customerManager.getCustomer(StringUtil.stringToInteger(customerId));
		List<CargoVO> cargoesList = cargoManager.getCargoVOByCustomer(customerId);
		
		CargoVO currentCargo = new CargoVO();
		List stockRecordList = new ArrayList();
		//if(cargoesList != null && cargoesList.size() > 0){
			
		stockRecordList = stockRecordManager.getStockRecordList(customerId,sDate,eDate);
		
		for(int i = 0;i < stockRecordList.size();i++){
			StockRecordVO vo = (StockRecordVO)stockRecordList.get(i);
			Calendar  calendar = Calendar.getInstance();
			calendar.setTime(vo.getTime());
			int day = calendar.get(Calendar.DAY_OF_MONTH);
			if(day == 6 ){
				StockRecordVO v = new  StockRecordVO();
				v.setInOut(Short.valueOf("2"));
				stockRecordList.add(i,v);	
				break;
			}
			
		}
		
		//上月结存
		List<MonthTotalVO> monthTotalList = cargoManager.getMonthTotalVOList(c,mDate);
		Map<String,Integer> map = new HashMap();
		//分类统计重量
		for(MonthTotalVO m:monthTotalList){
			if(map.containsKey(m.getChargeType())){
				Integer i = map.get(m.getChargeType()); 
				i = i + Integer.valueOf(m.getBalanceWeight());
				map.put(m.getChargeType(), i);
			}else{
				if(m.getBalanceWeight() != null){
					map.put(m.getChargeType(), Integer.valueOf(m.getBalanceWeight()));
				}
			}
		}
		
		
		/*StockRecordVO v = new  StockRecordVO();
		v.setInOut(Short.valueOf("3"));
		stockRecordList.add(v);	*/
	
		
		
		//	monthTotal = cargoManager.getMonthTotal(c,md,currentCargo.getId());
			
			
		//}else if(cargoesList != null && cargoesList.size() > 0 ){
			
		//	stockRecordList = stockRecordManager.get(customerId,sDate,eDate);
			
		//	monthTotal = cargoManager.getMonthTotal(c,md,currentCargo.getId());
			
			
		//}
		
		String stockRecordListJson = JsonUtil.list2json(stockRecordList);
		
		request.setAttribute("customer", c);
		request.setAttribute("stockRecord.list", stockRecordList);
		request.setAttribute("cargoes.list", cargoesList);
		//request.setAttribute("date.list", dateList);
		request.setAttribute("stockRecordListJson", stockRecordListJson);
		request.setAttribute("month", d);
		request.setAttribute("day_1", day_1);
		request.setAttribute("day_2", day_2);
		
		request.setAttribute("monthTotalMap", map);
		return mapping.findForward("view");
	}
}