/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sclk.scwms.web.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.sclk.scwms.common.StringUtil;
import com.sclk.scwms.model.Warehouse;
import com.sclk.scwms.service.WarehouseManager;
import com.sclk.scwms.web.form.LocationForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-24-2010
 * 
 * XDoclet definition:
 * @struts.action path="/customer" name="customerForm" input="/jsp/customer.jsp" scope="request" validate="true"
 */
public class LocationAction extends BaseAction {
	
	private WarehouseManager manager;

    public void setManager(WarehouseManager manager) {
    	this.manager = manager;
    }
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward view(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LocationForm locationForm = (LocationForm) form;// TODO Auto-generated method stub
		
		String subWarehouseId  = request.getParameter("subWarehouseId");
		
		
		if(subWarehouseId == null){ 
			subWarehouseId  = (String) request.getAttribute("subWarehouseId");
		}
		Integer id = StringUtil.stringToInteger(subWarehouseId);
		
		
		
		List mList = null;
		String subWarehouseName = "";
		String warehouseName = "";
		String warehouseId = "";
		if(id != null){ 
			 
			 mList = manager.getLocationList(id);
			 
			 Warehouse w = manager.getWarehouse(id);
			 if(w != null){ 
				 subWarehouseName = w.getName();
				 Warehouse w1 = manager.findByParentKey(w.getParentKey());
				 warehouseName = w1.getName();
				 warehouseId = w1.getId().toString();
			 }
		}
		 
		
		
		request.setAttribute("location.list", mList);
		
		request.setAttribute("subWarehouseName",subWarehouseName);
		request.setAttribute("subWarehouseId", subWarehouseId);
		request.setAttribute("warehouseName",warehouseName);
		request.setAttribute("warehouseId", warehouseId);
		return mapping.findForward("view");
		
	}
	
	
	
}