/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sclk.scwms.web.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.sclk.scwms.common.DateUtil;
import com.sclk.scwms.common.StringUtil;
import com.sclk.scwms.model.Cargo;
import com.sclk.scwms.model.MonthTotal;
import com.sclk.scwms.model.MonthWarehouse;
import com.sclk.scwms.service.CargoManager;
import com.sclk.scwms.service.CustomerManager;
import com.sclk.scwms.service.MonthTotalManager;
import com.sclk.scwms.service.MonthWarehouseManager;
import com.sclk.scwms.service.SyscodeManager;
import com.sclk.scwms.service.WarehouseManager;
import com.sclk.scwms.vo.CargoVO;
import com.sclk.scwms.web.form.MonthWarehouseEditForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-23-2010
 * 
 * XDoclet definition:
 * @struts.action path="/cargo" name="cargoForm" input="/jsp/cargo.jsp" parameter="method" scope="request" validate="true"
 * @struts.action-forward name="init" path="/jsp/cargo.jsp"
 */
public class MonthWarehouseEditAction extends BaseAction {
	
	private CargoManager manager;

    public void setManager(CargoManager manager) {
    	this.manager = manager;
    }
    private SyscodeManager scmanager;

    public void setScmanager(SyscodeManager manager) {
    	this.scmanager = manager;
    }
    private CustomerManager customerManager;

    public void setCustomerManager(CustomerManager manager) {
    	this.customerManager = manager;
    }
    
    private MonthTotalManager monthTotalManager;

    public void setMonthTotalManager(MonthTotalManager manager) {
    	this.monthTotalManager = manager;
    }
    private WarehouseManager warehouseManager;

    public void setWarehouseManager(WarehouseManager manager) {
    	this.warehouseManager = manager;
    }
    private MonthWarehouseManager monthWarehouseManager;

    public void setMonthWarehouseManager(MonthWarehouseManager manager) {
    	this.monthWarehouseManager = manager;
    }
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward init(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		MonthWarehouseEditForm monthWarehouseEditForm = (MonthWarehouseEditForm) form;// TODO Auto-generated method stub
		
		String cargoId  = request.getParameter("cargoId");
		String month  = request.getParameter("month");
		String monthTotalId  = request.getParameter("monthTotalId");
		
		MonthTotal m = new MonthTotal();
		Integer mId = StringUtil.stringToInteger(monthTotalId);;
		if(mId != null){
			m = monthTotalManager.getMonthTotal(StringUtil.stringToInteger(monthTotalId));
			
		}
		
		
		monthWarehouseEditForm.setCargoId(cargoId);
		
		CargoVO c = manager.getCargoVO(StringUtil.stringToInteger(cargoId));
		monthWarehouseEditForm.setCargoName(c.getName()+"("+c.getWeight()+"kg/"+c.getUnit()+")");
		monthWarehouseEditForm.setCustomerId(c.getCustomerId());
		
		monthWarehouseEditForm.setMonth(month);
		if(mId != null && m != null){
			
			monthWarehouseEditForm.setMonthTotalId(m.getId().toString());
			monthWarehouseEditForm.setBalanceQuantity(m.getBalanceQuantity());
			monthWarehouseEditForm.setBalanceWeight(m.getBalanceWeight());
		}
		
		List mList = warehouseManager.getWarehouseList();
		
		
		/**
		 * customerId=182&cargoId=2&month=200910
		 */
		request.setAttribute("cargoId", cargoId);
		request.setAttribute("month", month);
		request.setAttribute("stockWarehouse.list", mList);
		
		return mapping.findForward("init");
	}
	
	public ActionForward save(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		MonthWarehouseEditForm monthWarehouseEditForm = (MonthWarehouseEditForm) form;// TODO Auto-generated method stub
		
		MonthWarehouse m = new MonthWarehouse();
		
		m.setMonthTotalId(StringUtil.stringToInteger(monthWarehouseEditForm.getMonthTotalId()));
		m.setWarehouseId(StringUtil.stringToInteger(monthWarehouseEditForm.getWarehouseId()));
		
		m.setQuantity(StringUtil.stringToInteger(monthWarehouseEditForm.getQuantity()));
		m.setWeight(StringUtil.stringToInteger(monthWarehouseEditForm.getWeight()));
		monthWarehouseManager.sava(m);
		
		return mapping.findForward(success);
	}
	
	
}