/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sclk.scwms.web.action;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.sclk.scwms.common.DateUtil;
import com.sclk.scwms.common.StringUtil;
import com.sclk.scwms.model.Customer;
import com.sclk.scwms.service.CargoManager;
import com.sclk.scwms.service.CustomerManager;
import com.sclk.scwms.service.MonthTotalManager;
import com.sclk.scwms.service.StockRecordManager;
import com.sclk.scwms.vo.CargoVO;
import com.sclk.scwms.web.form.MonthTotalForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-06-2010
 * 
 * XDoclet definition:
 * @struts.action path="/stockItems" name="stockItemsForm" input="/jsp/stockItems.jsp" scope="request" validate="true"
 */
public class MonthTotalAction extends BaseAction {
	
	private StockRecordManager stockRecordManager;

    public void setStockRecordManager(StockRecordManager manager) {
    	this.stockRecordManager = manager;
    }
    
    private CustomerManager customerManager;

    public void setCustomerManager(CustomerManager manager) {
    	this.customerManager = manager;
    }
    
    private CargoManager cargoManager;

    public void setCargoManager(CargoManager manager) {
    	this.cargoManager = manager;
    }
    
    private MonthTotalManager monthTotalManager;

    public void setMonthTotalManager(MonthTotalManager manager) {
    	this.monthTotalManager = manager;
    }
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward view(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		MonthTotalForm monthTotalForm = (MonthTotalForm) form;// TODO Auto-generated method stub
		
		
		String customerId = request.getParameter("customerId");
		String month = request.getParameter("month");
		
		Date d = new Date();
		if(month != null){
			d = DateUtil.stringToDate("yyyyMM", month);
		}
		
		Customer customer = new Customer();
		customer.setId(StringUtil.stringToInteger(customerId));
		List monthTotalList = cargoManager.getMonthTotalVOList(customer,d);
		
		
		Customer c = customerManager.getCustomer(StringUtil.stringToInteger(customerId));
		List<CargoVO> cargoesList = cargoManager.getCargoVOByCustomer(customerId);
		
		request.setAttribute("customer", c);
		request.setAttribute("monthTotal.list", monthTotalList);
		request.setAttribute("month", d);
		return mapping.findForward("view");
	}
}