/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sclk.scwms.web.action;

import java.util.Date;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.sclk.scwms.common.DateUtil;
import com.sclk.scwms.service.WarehouseManager;
import com.sclk.scwms.web.form.StockWarehouseForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-06-2010
 * 
 * XDoclet definition:
 * @struts.action path="/stockItems" name="stockItemsForm" input="/jsp/stockItems.jsp" scope="request" validate="true"
 */
public class StockWarehouseAction extends BaseAction {
	
	private WarehouseManager warehouseManager;

    public void setWarehouseManager(WarehouseManager manager) {
    	this.warehouseManager = manager;
    }
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward view(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		StockWarehouseForm stockWarehouseForm = (StockWarehouseForm) form;// TODO Auto-generated method stub
		
		List mList = warehouseManager.getWarehouseListWithTotalWeightAndCustomer();
		
		request.setAttribute("stockWarehouse.list", mList);
		
		return mapping.findForward("view");
	}
	
	public ActionForward chart(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		StockWarehouseForm stockWarehouseForm = (StockWarehouseForm) form;// TODO Auto-generated method stub
		
		List mList = warehouseManager.getWarehouseListWithTotalWeight();
		Date now = new Date();
		Date sMonth = new Date();
		
		now = DateUtil.stringToDate("2009-10-18");
		
		request.setAttribute("stockWarehouse.list", mList);
		
		return mapping.findForward("chart");
	}
}