/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sclk.scwms.web.action;

import java.io.UnsupportedEncodingException;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.sclk.scwms.common.StringUtil;
import com.sclk.scwms.model.Customer;
import com.sclk.scwms.service.CustomerManager;
import com.sclk.scwms.service.StockRecordManager;
import com.sclk.scwms.web.form.StockCustomerForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-06-2010
 * 
 * XDoclet definition:
 * @struts.action path="/stockItems" name="stockItemsForm" input="/jsp/stockItems.jsp" scope="request" validate="true"
 */
public class StockCustomerAction extends BaseAction {
	
	private StockRecordManager stockRecordManager;

    public void setStockRecordManager(StockRecordManager manager) {
    	this.stockRecordManager = manager;
    }
    
    private CustomerManager customerManager;

    public void setCustomerManager(CustomerManager manager) {
    	this.customerManager = manager;
    }
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward view(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		StockCustomerForm stockCustomerForm = (StockCustomerForm) form;// TODO Auto-generated method stub
		//String customerId = request.getParameter("customerId");
		
		List customerList = customerManager.getCustomers();
		//Customer c = customerManager.getCustomer(StringUtil.stringToInteger(customerId));
		
		//request.setAttribute("customer.name", c == null? "":c.getName());
		request.setAttribute("customer.list", customerList);
		
		return mapping.findForward("view");
	}
	
	public ActionForward query(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws UnsupportedEncodingException {
		StockCustomerForm stockCustomerForm = (StockCustomerForm) form;// TODO Auto-generated method stub
		String keyword = request.getParameter("keyword");
		
		List customerList = null;
		
		if(keyword!=null){
			keyword = new String(keyword.getBytes("ISO8859_1"),"utf-8");
		}
		customerList = customerManager.findBykeyword(keyword);
		
		//request.setAttribute("customer.name", c == null? "":c.getName());
		request.setAttribute("keyword",keyword);
		request.setAttribute("customer.list",customerList);
		
		return mapping.findForward("view");
	}
}