/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sclk.scwms.web.action;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.sclk.scwms.common.StringUtil;
import com.sclk.scwms.service.CargoManager;
import com.sclk.scwms.service.CustomerManager;
import com.sclk.scwms.service.StockPostionManager;
import com.sclk.scwms.service.StockRecordManager;
import com.sclk.scwms.service.UserManager;
import com.sclk.scwms.vo.CargoVO;
import com.sclk.scwms.web.form.StockPostionForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-25-2010
 * 
 * XDoclet definition:
 * @struts.action path="/stockIn" name="stockInForm" input="/jsp/stockIn.jsp" scope="request" validate="true"
 * @struts.action-forward name="init" path="/jsp/stockIn.jsp"  
 */
public class StockPostionAction extends BaseAction {
	
	private CustomerManager customerManager;

    public void setCustomerManager(CustomerManager manager) {
    	this.customerManager = manager;
    }
    private UserManager userManager;

    public void setUserManager(UserManager manager) {
    	this.userManager = manager;
    }
    
    private StockRecordManager stockRecordManager;
    
    public void setStockRecordManager(StockRecordManager stockRecordManager) {
		this.stockRecordManager = stockRecordManager;
	}
    
    private CargoManager cargoManager;

    public void setCargoManager(CargoManager manager) {
    	this.cargoManager = manager;
    }
    
    private StockPostionManager stockPostionManager;

    public void setStockPostionManager(StockPostionManager manager) {
    	this.stockPostionManager = manager;
    }
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward init(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		StockPostionForm stockPostionForm = (StockPostionForm) form;// TODO Auto-generated method stub
		
		String index = request.getParameter("index");
		request.setAttribute("index", index);
		return mapping.findForward("init");
	}
	public ActionForward save(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		StockPostionForm stockPostionForm = (StockPostionForm) form;// TODO Auto-generated method stub
		String index = request.getParameter("index");
		String[] postionNumberArr = request.getParameterValues("postionNumber");
		String[] quantityArr = request.getParameterValues("quantity");
		int i = postionNumberArr.length;
		
		String postionQuantityList = "";
		
		for(int j = 0; j < i; j++){
			if(!quantityArr[j].equals("")){
				String postionNumber = postionNumberArr[j];
				String quantity = quantityArr[j];
				String postionQuantity = postionNumber + ":" + quantity;
				
				postionQuantityList = postionQuantityList + postionQuantity + ",";
			}
		}
		
		List<CargoVO> l = (List<CargoVO>) request.getSession().getAttribute("cargoList");
		if(l == null){
			l = new ArrayList();
		}
		CargoVO cargoVO = l.get(StringUtil.stringToInteger(index));
		
		cargoVO.setPostionQuantityList(postionQuantityList);
		request.getSession().setAttribute("cargoList", l);
		
		return null;
	}
	
	public ActionForward check(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		StockPostionForm stockPostionForm = (StockPostionForm) form;// TODO Auto-generated method stub
		
		List list = stockPostionManager.get();
		request.setAttribute("list", list);
		return mapping.findForward("check");
	}
}