/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sclk.scwms.web.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.sclk.scwms.model.Syscode;
import com.sclk.scwms.service.SyscodeManager;
import com.sclk.scwms.web.form.SyscodeForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-19-2010
 * 
 * XDoclet definition:
 * @struts.action path="/dictionary" name="dictionaryForm" input="/WEB_INF/jsp/dictionary.jsp" scope="request"
 */
public class SyscodeAction extends BaseAction {
	
	 private SyscodeManager manager;

    public void setManager(SyscodeManager manager) {
    	this.manager = manager;
    }
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	
	
	public ActionForward view(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		SyscodeForm syscodeForm = (SyscodeForm) form;// TODO Auto-generated method stub
		
		//
		String key  = request.getParameter("key");
		Syscode syscode = manager.get(key);
		
		Syscode d = manager.get(1);
		manager.buildSyscode(d);
		String treeview = manager.buildTreeview(d);
		
		
		request.setAttribute("syscode", syscode);
		request.setAttribute("treeview", treeview);
		return mapping.findForward("view");
	}
	
	
}