/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sclk.scwms.web.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.sclk.scwms.common.StringUtil;
import com.sclk.scwms.model.Syscode;
import com.sclk.scwms.service.SyscodeManager;
import com.sclk.scwms.web.form.SyscodeEditForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-19-2010
 * 
 * XDoclet definition:
 * @struts.action path="/dictionaryEdit" name="dictionaryEditForm" input="/WEB-INF/jsp/dictionaryEdit.jsp" scope="request" validate="true"
 */
public class SyscodeEditAction extends BaseAction {
	
	 private SyscodeManager manager;

	    public void setManager(SyscodeManager manager) {
		this.manager = manager;
	 }
	
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward modifyInit(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		SyscodeEditForm dictionaryEditForm = (SyscodeEditForm) form;// TODO Auto-generated method stub
		
		String id  = request.getParameter("syscodeId");
		
		Syscode s = manager.get(StringUtil.stringToInteger(id));
		dictionaryEditForm.setId(s.getId().toString());
		dictionaryEditForm.setKey(s.getCodeKey());
		dictionaryEditForm.setValue(s.getCodeValue());
		dictionaryEditForm.setParentKey(s.getParentKey());
		dictionaryEditForm.setOrderId(s.getOrderId());
		dictionaryEditForm.setMemo(s.getMemo());
		return mapping.findForward("init");
	}
	
	public ActionForward createInit(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		SyscodeEditForm dictionaryEditForm = (SyscodeEditForm) form;// TODO Auto-generated method stub
		
		String id  = request.getParameter("syscodeId");
		
		Syscode parentSyscode = manager.get(StringUtil.stringToInteger(id));
		
		dictionaryEditForm.setParentKey(parentSyscode.getCodeKey());
		
		return mapping.findForward("init");
	}
	public ActionForward save(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		SyscodeEditForm sForm = (SyscodeEditForm) form;// TODO Auto-generated method stub
		Syscode d = new Syscode();
		d.setId(StringUtil.stringToInteger(sForm.getId()));
		d.setCodeKey(sForm.getKey());
		d.setCodeValue(sForm.getValue());
		d.setParentKey(sForm.getParentKey());
		d.setOrderId(sForm.getOrderId());    
		d.setMemo(sForm.getMemo());
		
		manager.sava(d);
		return mapping.findForward("save");
	}
	
}