/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sclk.scwms.web.action;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.sclk.scwms.common.DateUtil;
import com.sclk.scwms.common.StringUtil;
import com.sclk.scwms.model.Customer;
import com.sclk.scwms.model.Users;
import com.sclk.scwms.service.SystemLogManager;
import com.sclk.scwms.web.form.ChargeDetailForm;
import com.sclk.scwms.web.form.SystemLogForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-28-2014
 * 
 * XDoclet definition:
 * @struts.action path="/systemLog" name="systemLogForm" input="/jsp/systemLog.jsp" scope="request" validate="true"
 */
public class SystemLogAction extends BaseAction {

	private SystemLogManager systemLogManager;
    
    public void setSystemLogManager(SystemLogManager systemLogManager) {
		this.systemLogManager = systemLogManager;
	}
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	
	
	public ActionForward query(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		SystemLogForm systemLogForm = (SystemLogForm) form;// TODO Auto-generated method stub
		
		String startDate = request.getParameter("startDate");
		String endDate = request.getParameter("endDate");
		String type = request.getParameter("type");
		
		List systemLogList = systemLogManager.getSystemLogs(startDate,endDate,type);
		
		request.setAttribute("startDate",startDate);
		request.setAttribute("endDate",endDate);
		request.setAttribute("systemLog.list",systemLogList);
		
		return mapping.findForward("query");
		
	}
	
	public ActionForward onlineUsers(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		SystemLogForm systemLogForm = (SystemLogForm) form;// TODO Auto-generated method stub
		
		HttpSession session = request.getSession();
		ServletContext application = session.getServletContext();
		List onlineUserList = new ArrayList();
		onlineUserList = (List) application.getAttribute("onlineUserList");
		if(onlineUserList == null){
			onlineUserList = new ArrayList();
			application.setAttribute("onlineUserList",onlineUserList);
        }
		
		request.setAttribute("onlineUser.list",onlineUserList);
		
		return mapping.findForward("onlineUsers");
		
	}
}