/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sclk.scwms.web.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.sclk.scwms.common.StringUtil;
import com.sclk.scwms.model.Warehouse;
import com.sclk.scwms.service.WarehouseManager;
import com.sclk.scwms.web.form.WarehouseForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-24-2010
 * 
 * XDoclet definition:
 * @struts.action path="/customer" name="customerForm" input="/jsp/customer.jsp" scope="request" validate="true"
 */
public class WarehouseAction extends BaseAction {
	
	private WarehouseManager manager;

    public void setManager(WarehouseManager manager) {
    	this.manager = manager;
    }
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward view(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		WarehouseForm warehouseForm = (WarehouseForm) form;// TODO Auto-generated method stub
		
		String warehouseId  = request.getParameter("warehouseId");
		
		Integer id = StringUtil.stringToInteger(warehouseId);
		
		Warehouse w = null;
		if(id != null){ 
			w = manager.getMainWarehouse(id);
		}
		
		if(w != null){
			warehouseForm.setWarehouse(w);
			return mapping.findForward("subView");
			
		}
		
		List mList = manager.getMainWarehouseList();
		warehouseForm.setWarehouseList(mList);
		
		return mapping.findForward("view");
		
	}
	
	
	
}