/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sclk.scwms.web.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.sclk.scwms.common.StringUtil;
import com.sclk.scwms.model.Warehouse;
import com.sclk.scwms.service.SyscodeManager;
import com.sclk.scwms.service.WarehouseManager;
import com.sclk.scwms.web.form.WarehouseEditForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-23-2010
 * 
 * XDoclet definition:
 * @struts.action path="/warehouse" name="warehouseForm" input="/jsp/warehouse.jsp" parameter="method" scope="request" validate="true"
 * @struts.action-forward name="init" path="/jsp/warehouse.jsp"
 */
public class WarehouseEditAction extends BaseAction {
	
	private WarehouseManager manager;

    public void setManager(WarehouseManager manager) {
    	this.manager = manager;
    }
	
	private SyscodeManager scmanager;

    public void setScmanager(SyscodeManager manager) {
    	this.scmanager = manager;
    }
    
	
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward init(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		WarehouseEditForm warehouseEditForm = (WarehouseEditForm) form;// TODO Auto-generated method stub
		
		String warehouseId  = request.getParameter("warehouseId");
		
		Integer id = StringUtil.stringToInteger(warehouseId);
		Warehouse w = null;
		if(id != null){
			w = manager.getWarehouse(id);
		}
		
		
		if(w != null){	
			warehouseEditForm.setId(w.getId().toString());
			warehouseEditForm.setName(w.getName());
			warehouseEditForm.setSerialNumber(w.getSerialNumber());
			warehouseEditForm.setSerialKey(w.getSerialKey());
			warehouseEditForm.setParentKey(w.getParentKey());
			warehouseEditForm.setType(w.getType());
			warehouseEditForm.setTemperature(w.getTemperature());
			warehouseEditForm.setSize(w.getSize());
			warehouseEditForm.setOrderId(w.getOrderId());
			warehouseEditForm.setArea(w.getArea());
			warehouseEditForm.setVolume(w.getVolume());
			warehouseEditForm.setLength(w.getLength());
			warehouseEditForm.setWidth(w.getWidth());
			warehouseEditForm.setHeight(w.getHeight());
			warehouseEditForm.setMemo(w.getMemo());
		}	
		
		List typeList = scmanager.getChildren("warehouseType");
		warehouseEditForm.setTypeList(typeList);
		
		return mapping.findForward("init");
	}
	public ActionForward initSub(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		WarehouseEditForm warehouseEditForm = (WarehouseEditForm) form;// TODO Auto-generated method stub
		
		String warehouseId  = request.getParameter("warehouseId");
				
		Integer id = StringUtil.stringToInteger(warehouseId);
		Warehouse w = null;
		if(id != null){
			w = manager.getWarehouse(id);
		}
		
		if(w != null ){
			
			if(!w.getParentKey().equals("0")){
			
				warehouseEditForm.setId(w.getId().toString());
				warehouseEditForm.setName(w.getName());
				warehouseEditForm.setSerialNumber(w.getSerialNumber());
				warehouseEditForm.setSerialKey(w.getSerialKey());
				warehouseEditForm.setParentKey(w.getParentKey());
				warehouseEditForm.setType(w.getType());
				warehouseEditForm.setTemperature(w.getTemperature());
				warehouseEditForm.setSize(w.getSize());
				warehouseEditForm.setOrderId(w.getOrderId());
				warehouseEditForm.setArea(w.getArea());
				warehouseEditForm.setVolume(w.getVolume());
				warehouseEditForm.setLength(w.getLength());
				warehouseEditForm.setWidth(w.getWidth());
				warehouseEditForm.setHeight(w.getHeight());
				warehouseEditForm.setMemo(w.getMemo());
			}else{
				
				warehouseEditForm.setParentKey(w.getSerialKey());
				
			}
			
		}	
		
		List typeList = scmanager.getChildren("warehouseType");
		warehouseEditForm.setTypeList(typeList);
		
		return mapping.findForward("initSub");
	}
	
	public ActionForward save(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		WarehouseEditForm warehouseEditForm = (WarehouseEditForm) form;// TODO Auto-generated method stub
		
		Warehouse w = new Warehouse();
		
		w.setId(StringUtil.stringToInteger(warehouseEditForm.getId()));
		w.setName(warehouseEditForm.getName());
		w.setSerialNumber(warehouseEditForm.getSerialNumber());
		w.setSerialKey(warehouseEditForm.getSerialKey());
		w.setParentKey(warehouseEditForm.getParentKey());
		w.setType(warehouseEditForm.getType());
		w.setTemperature(warehouseEditForm.getTemperature());
		w.setSize(warehouseEditForm.getSize());
		w.setOrderId(warehouseEditForm.getOrderId());
		w.setArea(warehouseEditForm.getArea());
		w.setVolume(warehouseEditForm.getVolume());
		w.setLength(warehouseEditForm.getLength());
		w.setWidth(warehouseEditForm.getWidth());
		w.setHeight(warehouseEditForm.getHeight());
		w.setMemo(warehouseEditForm.getMemo());
		manager.sava(w);
		
		return mapping.findForward(success);
	}
}